---
title: "Lab 10 Intro"
date: "`r Sys.Date()`"
output: ioslides_presentation
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)
library("jpeg")
library(tidyverse)
```

## Seating & Set-up
1. Please make sure that you sit next to your group members for the rest of the quarter.
2. Please set-up your computer as normal.

## Warm-up
1. Please load the homerange data `Tamburelloetal_HomeRangeDatabase.csv`
```{r}
homerange <- readr::read_csv("data/Tamburelloetal_HomeRangeDatabase.csv")
```

2. Show the min, mean, and max log10.mass by taxonomic class in the dataset.
```{r}
homerange %>% 
  group_by(taxon) %>% 
  summarise(log10.mass_mean = mean(log10.mass)) %>% 
  arrange(taxon)
```
```{r}
homerange %>% 
  group_by(taxon) %>% 
  top_n(1, log10.mass) %>% 
  select(taxon, log10.mass) %>% 
  arrange(taxon)
```
```{r}
homerange %>% 
  group_by(taxon) %>% 
  top_n(-1, log10.mass) %>% 
  select(taxon, log10.mass) %>% 
  arrange(taxon)
```
 
3. Make a plot that best summarizes this output.
```{r}
homerange %>% 
  ggplot(aes(x=class, y= log10.mass))+geom_boxplot()
```

