---
title: "Lab 11 Intro"
date: "`r Sys.Date()`"
output: ioslides_presentation
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)
library("jpeg")
library("tidyverse")
```

## Seating & Set-up
1. Please make sure that you sit next to your group members for the rest of the quarter.
2. Please set-up your computer as normal.

## Warm-up
For this warm-up, please use the `heartrate` data. Be sure to label your plots!
```{r}
heartrate <- readr::read_csv("data/heartrate.csv")
heartrate
```

1. Make a plot that compares the heartrate of patients for drug a.
```{r}
heartrate %>% 
  ggplot(aes(x= patient, y=a, fill = patient))+geom_col()+
  labs(title = "Drug A Heartrates",
       x= "Patient Name",
       y= "Heartrate")
  
```

2. Make a plot that compares heartrate (as a range) for each drug.
```{r}
heartrate %>% 
  pivot_longer(a:d,
               names_to = "drug",
               values_to = "heart_rate") %>% 
  ggplot(aes(x=drug, y= heart_rate, fill = drug))+geom_boxplot()
```

